### PR TITLE
Adds Global Skeleton UI and Prettier

### PR DESCRIPTION
**Pull request by lilyx13**

### CODE REVIEW

**Comment by lilyx13** [comment]
@acidtone This is ready for review.

I added a little bit of styling to the sidebar.

This only sets up the global layout. I looked at how Skeleton and Svelte's sites' use the "On This Page" RH sidebar and it looks like it's not at the same level.

I also added iconify so we have a big library of icons to use.

**Comment by lilyx13** [comment]
I went a bit out of scope but figured the changes were top level enough to make sense. I also just added accordions to the schedule.

**Comment by acidtone** [comment]
A couple things I noticed:
1. Clicking on the courses in the side bar don't refresh the content after the 1st click
2. The side bar on the lesson plans should show the course schedule?

Not sure if these need to be fixed before a merge.

**Comment by lilyx13** [comment]
I haven't touched the lesson plan stuff yet.

yeah this is weird. the url is changing and the body is refreshing but content isn't changing. Will check into this

**Comment by lilyx13** [comment]
Ok, I think it has to do with how svelte handles reactivity. I'm looking at [how skeleton implements something similar](https://github.com/skeletonlabs/skeleton/blob/dev/sites/skeleton.dev/src/lib/components/DocsSidebar/DocsSidebar.svelte)

**Comment by lilyx13** [comment]
Good to merge @ meeting w/ @acidtone aug 18

**Pull request merged**
